import test from 'node:test';import assert from 'node:assert/strict';
import {createPlayer,advanceYear,choose} from '../dist/src/engine.js';
import {emptyStats} from '../dist/src/stats.js';
import {setContract,prepareRenewal,signRenewal,salaryEstimate,calculateSalaryEvaluation,seasonSalaryValue,rookieContractTerms,evaluateRehabContract,rehabSalary,evaluateRosterReturn,SALARY_MODEL,CURRENCY} from '../dist/src/contracts.js';
import {settleSalary,settleIncome,settleSigningPayment,careerIncome,firstTeamAllowance} from '../dist/src/finance.js';
import {reviewEmployment,declineRehab} from '../dist/src/lifecycle.js';
import {simulateDailyRoster,mlbService} from '../dist/src/roster.js';
import {faService} from '../dist/src/free-agency.js';
import {validate} from '../dist/src/storage.js';
import {TEAMS} from '../dist/src/data.js';
function player(role='batter',rating=78){const s=createPlayer('契約検証',role,713);Object.assign(s,{stage:'pro',age:25,year:2033,team:TEAMS[0],salary:1200,proYears:4});for(const k in s.player.abilities){s.player.abilities[k]=rating;s.player.potential[k]=90;}s.player.pitchRole='starter';s.player.batterRole='regular';return s;}
function record(s,values={}){return {year:s.year,team:s.team,stage:s.stage,age:s.age,salary:s.salary,overall:78,pitchRole:s.player.pitchRole,batterRole:'regular',contractStatus:s.contractStatus,stats:{...emptyStats(),...values}};}
const bat={games:140,ab:500,hits:150,doubles:28,hr:25,bb:60,sb:15,rbi:80};
for(const [pay,rate] of [[420,.75],[1000,.75],[10000,.75],[10010,.6],[50000,.6]])test('通常更改の減額制限：'+pay+'万円',()=>{const s=player();s.salary=pay;assert.ok(salaryEstimate(s,record(s))>=Math.max(420,pay*rate));});
test('過去3年を評価し、単年不振でも実績を消さず3年低迷なら下がる',()=>{const s=player();s.salary=10000;const now=record(s);s.records=[{...record(s,bat),year:s.year-2},{...record(s,bat),year:s.year-1}];const good=calculateSalaryEvaluation(s,now).target;s.records=s.records.map(r=>({...r,stats:emptyStats()}));assert.ok(good>calculateSalaryEvaluation(s,now).target);});
test('前年年俸をアンカーに段階的昇給しFA市場には別の価格がある',()=>{const s=player();s.salary=1000;const r=record(s,{...bat,hr:40,hits:180});const renewal=salaryEstimate(s,r);assert.ok(renewal>1000&&renewal<=2500);assert.ok(salaryEstimate({...s},r,true)>renewal);});
for(const role of ['starter','reliever','closer'])test(role+'の継続的な投球実績を査定',()=>{const s=player('pitcher');s.player.pitchRole=role;const r=record(s,role==='starter'?{games:25,outs:480,er:50,so:160,allowedHits:140,allowedWalks:40,wins:11}:{games:60,outs:180,er:18,so:70,allowedHits:45,allowedWalks:15,holds:role==='reliever'?30:0,saves:role==='closer'?35:0});assert.ok(seasonSalaryValue(s,r)>6000);assert.ok(salaryEstimate(s,r)>s.salary);});
test('二軍中心や少数打席だけで億単位に上がらない',()=>{const s=player();const r=record(s,{games:8,ab:12,hits:7,hr:3});assert.ok(salaryEstimate(s,r)<5000);assert.ok(salaryEstimate(s,record(s))<2000);});
test('年齢だけで過去実績や前年年俸を最低額にしない',()=>{const s=player();s.age=39;s.salary=18000;assert.ok(salaryEstimate(s,record(s,bat))>=10800);});
test('契約金と支度金は初回のみ、生涯年俸とは別に計上',()=>{for(const type of ['支配下','育成']){const s=player(),offer={type,bonus:type==='育成'?300:8000};settleSigningPayment(s,offer);settleSigningPayment(s,offer);assert.equal(s.totalSalary,0);assert.equal(careerIncome(s),offer.bonus);assert.equal(s.incomeHistory[0][type==='育成'?'setupAllowance':'signingBonus'],offer.bonus);}});
test('年度精算と出来高を繰り返しても二重計上しない',()=>{const s=player();setContract(s,1200,3,'更改',null,{stat:'games',target:100,amount:300,label:'100試合'});const r=record(s,bat);r.firstTeamDays=150;settleSalary(s,r);settleSalary(s,r);settleIncome(s,r);settleIncome(s,r);assert.equal(s.totalSalary,1600);assert.equal(s.totalIncentives,300);assert.equal(careerIncome(s),1900);assert.equal(s.incomeHistory.length,1);assert.equal(s.salary,1200);});
test('追加報酬150日とFA145日を区別',()=>{assert.equal(firstTeamAllowance(1000,150),600);assert.ok(firstTeamAllowance(1000,145)<600);const s=player();s.records=[{...record(s),faDays:145}];assert.equal(faService(s).total,145);});
test('新人は順位と評価で異なる年俸・契約金、育成支度金は別枠',()=>{const a=rookieContractTerms({type:'支配下',rank:1,score:85}),b=rookieContractTerms({type:'支配下',rank:1,score:98});assert.ok(a.salary<b.salary&&a.bonus<b.bonus);assert.ok(b.salary<=1600&&b.bonus<=10000&&b.incentive.amount<=5000);const d=rookieContractTerms({type:'育成',rank:1,score:62});assert.ok(d.salary>=240&&d.salary<=500);assert.equal(d.setupAllowance,300);});
test('有望若手の長期手術で育成提示、保証契約中は変更しない',()=>{const s=player('pitcher');s.health={name:'肘靱帯再建手術',daysLeft:450,severe:true};s.drafts=[{team:s.team,rank:2}];const r=record(s);assert.equal(evaluateRehabContract(s,r).decision,'rehab');prepareRenewal(s,r);reviewEmployment(s,r);assert.equal(s.employment,null);assert.ok(s.contractOffers.some(o=>o.id==='rehab'));setContract(s,1200,3);prepareRenewal(s,r);assert.equal(s.contractOffers.length,0);assert.equal(s.salary,1200);});
test('スターの手術は自動育成240万円にせず支配下継続',()=>{const s=player('pitcher');s.salary=30000;s.age=29;s.health={name:'トミー・ジョン手術',daysLeft:450,severe:true};s.records=[record(s,{games:26,outs:540,er:50,so:190,allowedHits:130,allowedWalks:35,wins:15})];assert.equal(evaluateRehabContract(s,record(s)).decision,'retain');prepareRenewal(s,record(s));assert.ok(s.contractOffers.every(o=>!o.development));assert.ok(s.contractOffers[0].annual>=18000);});
test('高齢・低評価・故障前も数年低迷なら退団もある',()=>{const s=player('batter',35);s.age=38;s.health={name:'アキレス腱断裂',daysLeft:300,severe:true};s.records=[{...record(s),year:2031},record(s)];assert.equal(evaluateRehabContract(s,{...record(s),overall:35}).decision,'release');prepareRenewal(s,{...record(s),overall:35});reviewEmployment(s,{...record(s),overall:35});assert.equal(s.employment.type,'released');assert.ok(s.employment.options.length);});
test('育成年俸は過去実績を反映し、新人支度金を再支給しない',()=>{const s=player();s.salary=10000;s.health={name:'手術',daysLeft:400};const r=record(s);const annual=rehabSalary(s,r);assert.ok(annual>=1000);s.contractOffers=[{id:'rehab',annual,years:1,year:s.year,development:true}];signRenewal(s,'rehab');assert.equal(s.developmentReason,'rehab');assert.equal(s.totalSetupAllowance,0);assert.ok(s.timeline.some(t=>t.text.includes('支配下契約終了')));});
test('育成再契約辞退は引退強制でなく他の進路へ進む',()=>{const s=player();s.health={name:'手術',daysLeft:400};s.records=[record(s)];s.contractOffers=[{id:'rehab',annual:600,year:s.year}];declineRehab(s);assert.ok(s.employment.options.some(o=>o.role==='player'));assert.equal(s.retired,false);assert.throws(()=>declineRehab(s));});
test('複数年満了時にだけ再査定',()=>{const s=player();setContract(s,8000,3);prepareRenewal(s,record(s));assert.equal(s.salary,8000);s.year+=2;prepareRenewal(s,record(s));assert.ok(s.contractOffers.length);});
test('支配下復帰には回復・実戦・評価が必要、期限は7月31日',()=>{const s=player();s.contractStatus='development';const c={date:'2033-07-31',recovered:true,farmGames:20,roll:0};assert.equal(evaluateRosterReturn(s,c),true);assert.equal(evaluateRosterReturn(s,{...c,date:'2033-08-01'}),false);assert.equal(evaluateRosterReturn(s,{...c,farmGames:0}),false);assert.equal(evaluateRosterReturn(s,{...c,recovered:false}),false);assert.equal(evaluateRosterReturn(s,{...c,roll:.99}),false);});
test('日次シミュレーションで全休は一二軍ゼロ、育成中の一軍出場なし',()=>{const s=player();s.contractStatus='development';s.developmentReason='rehab';const r=simulateDailyRoster(s,0,{startDay:0,unavailableDays:500},true);assert.equal(r.games.first,0);assert.equal(r.games.second,0);assert.equal(s.contractStatus,'development');});
test('育成から実戦を経てシーズン中復帰し、復帰前一軍出場はゼロ',()=>{let returned=0;for(let i=1;i<=20;i++){const s=player();s.seed=i*771;s.contractStatus='development';s.developmentReason='rehab';const r=simulateDailyRoster(s,0,{startDay:0,unavailableDays:30},true);const p=r.transactions.find(t=>t.to==='registered');if(p){returned++;assert.ok(p.day>=30&&p.date.slice(5)<='07-31');assert.ok(r.days.filter(d=>d.day<p.day).every(d=>!d.onActive));assert.ok(s.salary>=420);}}assert.ok(returned>0);});
test('MLB最低78万ドルの固定円換算、172日サービスタイム',()=>{const s=player();s.stage='mlb';setContract(s,1);assert.equal(s.salary,780000*CURRENCY.usdJpy/10000);s.records=Array.from({length:6},(_,i)=>({stage:'mlb',year:2020+i,mlbServiceDays:172}));assert.equal(mlbService(s),6*172);});
test('旧セーブの契約新項目を安全に補完し、過去の入団金を捏造しない',()=>{const s=player();for(const k of ['signingPayments','totalSigningBonus','totalSetupAllowance','developmentReason','rehabContract','rehabReview','rosterReturn'])delete s[k];const v=validate(s);assert.equal(v.totalSigningBonus,0);assert.deepEqual(v.signingPayments,[]);assert.deepEqual(validate(structuredClone(v)),v);});

test('大怪我→育成合意→療養→支配下・一軍復帰まで既存進行でつながる',()=>{
 const s=player('pitcher',82);s.age=23;s.health={name:'肘靱帯再建手術',daysLeft:450,totalDays:450,severe:true};s.drafts=[{team:s.team,rank:2}];
 s.records=[{...record(s),year:s.year-1}];prepareRenewal(s,record(s));s.year++;signRenewal(s,'rehab');
 for(let i=0;i<3&&!s.retired;i++){
  s.nationalOfferYear=s.year;if(s.injuryAdvice)s.injuryAdvice=null;if(s.retirementAdvice)s.retirementAdvice.answered=true;
  if(s.contractOffers.length)signRenewal(s,s.contractOffers[0].id);advanceYear(s);
 }
 assert.ok(s.timeline.some(t=>t.text.includes('育成再契約')));assert.ok(s.timeline.some(t=>t.text.includes('支配下選手へ復帰')));assert.ok(s.records.some(r=>r.stats.games>0));
});

test('契約種別すらない旧育成セーブでも補完結果は安定',()=>{const s=player();s.salary=240;delete s.contractStatus;delete s.developmentReason;validate(s);assert.equal(s.contractStatus,'development');assert.equal(s.developmentReason,'performance');assert.deepEqual(validate(structuredClone(s)),s);});
