import fs from 'node:fs';
import {createHash} from 'node:crypto';
const read=name=>JSON.parse(fs.readFileSync('reports/'+name+'.json','utf8'));
const before=read('development-before'),after=read('development-after'),diversity=read('development-diversity');
const protectedFiles=read('development-protected-files');
const unchanged=Object.fromEntries(Object.entries(protectedFiles).map(([name,hash])=>[name,createHash('sha256').update(fs.readFileSync('dist/src/'+name+'.js')).digest('hex')===hash]));
const labels={genius:'天才率',pro:'プロ到達率',highSchoolPro:'高卒プロ率',breakout:'覚醒経験率',stagnation:'停滞経験率',injury:'一度以上の故障',major:'メジャー到達率',active35:'35歳以上のプロ出場',active40:'40歳以上のプロ出場',legacy:'名球会',retiredNumber:'永久欠番',entryAge:'平均プロ入り年齢',retirementAge:'平均引退年齢',injuryPerSeason:'1年度あたり平均故障件数'};
const comparison=Object.fromEntries(Object.keys(labels).map(k=>[k,{before:before.summary.all[k],after:after.summary.all[k],difference:+(after.summary.all[k]-before.summary.all[k]).toFixed(3)}]));
const baseline=JSON.parse(fs.readFileSync('tests/audit-baseline.json','utf8'));
const baselineHash=createHash('sha256').update(fs.readFileSync('tests/audit-baseline.json')).digest('hex');
const changed=baseline.filter(b=>after.baseline.find(a=>a.seed===b.seed&&a.role===b.role&&a.requestedRoute===b.route).finalHash!==b.sha256).length;
fs.writeFileSync('reports/development-comparison.json',JSON.stringify({baselineHash,changedBaselineCases:changed,protectedFilesUnchanged:unchanged,comparison},null,2));
const names={pro:'国内プロ（全期間）',university:'国内大学',overseas:'海外大学',corporate:'社会人',independent:'独立'};
const a=after.summary.all;
let text=`# 選手多様性・進路別成長 検証記録\n\n`;
text+=`## 比較方法\n\n変更前後で同じ200 Seed × 5希望進路、各1,000人生を比較。別途、異なる1,000 Seedで再確認。野手・投手は半数ずつ。選択肢に存在するオファーだけを使い、架空の契約・能力は投入しない。\n\n`;
text+=`検証用の操作方針は、32歳以降の怪我相談、33歳以降の不振時職員打診、35歳以降の引退勧告で引退。アマチュア再挑戦は30〜33歳まで。ゲームの強制引退条件を変更する方針ではない。希望進路に入れない場合の既存の代替進路も含む。\n\n`;
text+=`## 旧挙動との差\n\n| 指標 | 変更前 | 変更後 |\n|---|---:|---:|\n`;
for(const [k,label] of Object.entries(labels))text+=`| ${label} | ${comparison[k].before} | ${comparison[k].after} |\n`;
text+=`\n率の単位は%。年齢と故障件数は実数。故障経験率は小学生から引退までに一度でも軽傷を含む怪我をした割合であり、毎年の怪我確率ではない。\n\n`;
text+=`## 進路別（変更後の対応Seed群）\n\n| 経由先 | 人数 | 成長合計平均 | 年平均成長 | プロ到達% | ドラフト評価平均 | その後のプロ年数 | 海外到達% |\n|---|---:|---:|---:|---:|---:|---:|---:|\n`;
for(const [route,r] of Object.entries(a.routes))text+=`| ${names[route]} | ${r.n} | ${r.meanGrowth} | ${r.annualGrowth} | ${r.proRate} | ${r.draftScore??'—'} | ${r.proYears} | ${r.majorRate} |\n`;
text+=`\n成長は既存periodResults.changesの役割別能力平均を集計（直接イベントや重傷の能力損失を全て含む総合能力差ではない）。国内プロの負値は晩年の衰えを含む。経由先は重複集計・再在籍を含み、進路選択時の能力や入団可否が異なるため、進路そのものの因果効果・成功保証ではない。高卒プロは全人生の${a.highSchoolPro}%。\n\n`;
text+=`独立の到達率には入団テストによる選抜、既に高校でプロ指名された選手の自主選択、30歳までの再挑戦が強く影響する。戦力外時の育成契約保証による迂回経路は修正したが、条件付き到達率は依然高い。入団可否・ドラフト計算を成功率目標のために変えていない。\n\n`;
text+=`## 多様性（別の1,000 Seed）\n\n| 実績から判定した例 | 件数 |\n|---|---:|\n`;
const patterns={earlyComplete:'高校時点で完成域',collegeGrowth:'大学で能力平均10以上成長',corporateBloom:'社会人で覚醒',independentToPro:'独立経由でプロ',noPro:'プロ未到達',topDraftFailure:'上位指名後に基準活躍・受賞なし',lowDraftStar:'下位・育成指名後に3年以上活躍',lateStar:'高校未完成から28歳以降に好成績',overseasFailure:'海外で基準活躍・受賞なし',overseasSuccess:'海外で3年以上活躍',injurySetback:'重傷経験',longCareer:'40歳以降にプロ出場'};
for(const [key,label] of Object.entries(patterns))text+=`| ${label} | ${diversity.summary.all.patterns[key]} |\n`;
text+=`\n成功判定は既存performanceに個人タイトルを併用し、救援・守備の受賞者を誤って失敗と数えない。表は重複し得る事後分類で、生成時のタイプ抽選ではない。変更前ファイルのpattern分類は当時の旧定義を保存しており、この件数比較には使わない。\n\n`;
text+=`## 天才と非天才（別の1,000 Seed）\n\n| 指標 | 天才 | 非天才 |\n|---|---:|---:|\n`;
for(const [key,label] of Object.entries(labels))text+=`| ${label} | ${diversity.summary.genius[key]} | ${diversity.summary.nonGenius[key]} |\n`;
text+=`\n天才${diversity.summary.genius.n}人、非天才${diversity.summary.nonGenius.n}人。天才でも能力上限未達・早い引退・名球会未到達がある。ただし本標本の天才は全員プロに到達し、上位指名後の完全な不振例は0。天才のプロ未到達を実証したとは扱わない。非天才のスター・名球会到達も確認。天才の希少性と既存高talent/potentialを残した結果、天才側の栄誉率は高め。\n\n`;
text+=`## 互換性・範囲\n\n旧baseline SHA-256: ${baselineHash}。再生成せず保存。旧実行の30件のハッシュ一致を確認した上で、新実行は${changed}件が変化。これは成長、故障、所属機会と追加メタデータによる意図した差。\n\n`;
text+=`未変更をハッシュ照合したファイル: ${Object.entries(unchanged).map(([k,v])=>k+'.js '+(v?'一致':'不一致')).join('、')}。統計・年俸・ドラフトの式、広告、UI、名称、シェアは維持。能力変化に伴う成績・契約の結果は変わる。意図しない差は回帰検証では検出していない。\n\n`;
text+=`実装・補完・設定の説明: ../DEVELOPMENT-SYSTEM.md。生データはdevelopment-before.json、development-after.json、development-diversity.json（全体・天才・非天才・経由別）。旧beforeとaudit-baselineは上書きしない。\n`;
fs.writeFileSync('reports/development-comparison.md',text);
console.log(JSON.stringify({baselineHash,changedBaselineCases:changed,protectedFilesUnchanged:unchanged}));
