import {advanceSeason as advanceYear} from './support.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {settle} from './support.js';
import {createPlayer,choose,retire} from '../dist/src/engine.js';
import {negotiate,acceptOffer,remain,eligibility,retirementReview} from '../dist/src/market.js';
import {validate} from '../dist/src/storage.js';
import {overall} from '../dist/src/growth.js';
import {money} from '../dist/src/format.js';
function graduate(seed){const s=createPlayer('検証','batter',seed);for(let i=0;i<6;i++)advanceYear(s);if(s.retired)return s;choose(s,seed%2?'club':'school');for(let i=0;i<3;i++)advanceYear(s);if(s.retired)return s;choose(s,seed%2?'mirai':'nagisa');for(let i=0;i<3;i++)advanceYear(s);return s;}
function veteran(seed=74){const s=createPlayer('契約テスト','batter',seed);s.stage='pro';s.team='東京スワローウィングス';s.player.arc='ordinary';s.age=30;s.year=2038;s.salary=12500;s.domesticEntry={route:'university',draftYear:2020};for(const k of Object.keys(s.player.abilities)){s.player.abilities[k]=84;s.player.potential[k]=95;}for(let i=0;i<7;i++){settle(s);advanceYear(s);}settle(s);s.records.forEach(r=>{if(r.stage==='pro')r.faDays=145;});return s;}
test('200人の高校卒業：プロ指名あり・なし・独立不合格が共存',()=>{let drafted=0,unavailable=0;const personalities=new Set(),ratings=[];for(let i=1;i<=200;i++){const s=graduate(i*3791);if(s.retired)continue;personalities.add(s.player.personality);ratings.push(overall(s));if(s.pending.draft.type!=='指名なし')drafted++;if(!s.pending.draft.independentOffer){unavailable++;assert.throws(()=>choose(s,'independent'));}}assert.ok(drafted>0&&drafted<150,`drafted=${drafted}`);assert.ok(unavailable>30);assert.equal(personalities.size,5);assert.ok(Math.max(...ratings)-Math.min(...ratings)>20);});
test('乱数シードによって成長が変わり、上限を超えない',()=>{const a=createPlayer('a','batter',100),b=structuredClone(a);a.player.personality='steady';b.player.personality='free';b.seed=987654;for(let i=0;i<6;i++){advanceYear(a);advanceYear(b);}assert.notDeepEqual(a.player.abilities,b.player.abilities);for(const [k,v]of Object.entries(a.player.abilities))assert.ok(v<=a.player.potential[k]);});
test('旧セーブの成績・乱数・所属・能力を保って新項目を補完',()=>{const s=graduate(147),old=structuredClone(s);delete old.player.personality;delete old.player.potential;delete old.player.environmentFit;delete old.player.growthPhase;delete old.moves;delete old.marketAttempts;delete old.market;delete old.retirementAdvice;delete old.lastAdviceYear;delete old.pending.draft.independentOffer;const seed=old.seed,ratings=structuredClone(old.player.abilities);validate(old);assert.equal(old.seed,seed);assert.deepEqual(old.player.abilities,ratings);assert.deepEqual(old.records,s.records);assert.ok(old.player.personality);assert.ok(Array.isArray(old.moves));});
test('FA資格、オファー固定、移籍承諾、重複移籍の防止',()=>{const s=veteran();assert.equal(eligibility(s,'fa'),'');const board=negotiate(s,'fa'),seed=s.seed;assert.deepEqual(negotiate(s,'fa'),board);assert.equal(s.seed,seed);if(!board.offers.length){remain(s);assert.equal(s.team,'東京スワローウィングス');}else{const oldRecords=structuredClone(s.records),o=board.offers[0];acceptOffer(s,o.id);assert.equal(s.team,o.team);assert.equal(s.salary,o.salary);assert.equal(s.moves.length,1);assert.deepEqual(s.records,oldRecords);assert.throws(()=>negotiate(s,'trade'));assert.throws(()=>acceptOffer(s,o.id));}});
test('交渉失敗・FA移籍・トレード・海外移籍と翌季成績を実行',()=>{const found={};for(let seed=1;seed<=120;seed++){const s=veteran(seed*451);for(const kind of ['trade','fa','posting']){const p=structuredClone(s);if(eligibility(p,kind))continue;const board=negotiate(p,kind);if(!board.offers.length){found.failure=true;continue;}acceptOffer(p,board.offers[0].id);found[kind]=true;if(kind==='posting'){assert.equal(p.stage,'mlb');advanceYear(p);assert.equal(p.records.at(-1).stage,'mlb');assert.ok(p.records.at(-1).salary>0);assert.equal(p.totalSalary,p.records.reduce((n,r)=>n+r.salary,0));}}}assert.deepEqual(found,{failure:true,trade:true,fa:true,posting:true});});
test('引退勧告は強制引退にせず、回答まで進行を止める',()=>{const s=veteran();s.age=41;s.lastAdviceYear=0;retirementReview(s,{overall:40,stats:{games:5}});assert.equal(s.retired,false);assert.ok(s.retirementAdvice);const year=s.year;advanceYear(s);assert.equal(s.year,year);s.retirementAdvice.answered=true;advanceYear(s);assert.equal(s.year,year+1);assert.equal(retire(s),true);});
test('学生途中の任意引退も成績を残す・金額表示',async()=>{const {advance}=await import('../dist/src/engine.js');const s=createPlayer('引退検証','batter',123);advance(s);const games=s.current.games;assert.ok(games>0);retire(s);assert.equal(s.records[0].stats.games,games);assert.equal(s.records[0].partial,true);assert.equal(money(12500),'1億2,500万円');assert.equal(money(20000),'2億円');assert.equal(money(850),'850万円');});
