import test from 'node:test';
import assert from 'node:assert/strict';
import {createPlayer} from '../dist/src/engine.js';
import {overseasRookieTerms,signOverseasRookie,setContract,prepareRenewal,signRenewal,SALARY_MODEL} from '../dist/src/contracts.js';
import {settleSalary,settleSigningPayment,settleIncome} from '../dist/src/finance.js';
import {simulateDailyRoster} from '../dist/src/roster.js';
import {migrateCareer} from '../dist/src/lifecycle.js';
import {emptyStats} from '../dist/src/stats.js';
function rookie(){const s=createPlayer('海外新人','batter',12345);Object.assign(s,{stage:'mlb',year:2031,age:22,team:'ボストン・レッドベアーズ',proEntry:{route:'overseasDirect',year:2031}});const terms=overseasRookieTerms(85,3);signOverseasRookie(s,terms);return s;}
function record(s,roster){return {year:s.year,age:s.age,team:s.team,stage:'mlb',salary:s.salary,overall:70,stats:emptyStats(),dailyRoster:roster};}
test('overseas rookie starts outside 40-man at minor pay; bonus is separate and idempotent',()=>{const s=rookie(),o=overseasRookieTerms(85,3);assert.equal(s.salary,450);assert.equal(s.mlbRoster.on40,false);settleSigningPayment(s,o);settleSigningPayment(s,o);assert.equal(s.totalSigningBonus,o.bonus);assert.equal(s.totalSalary,0);assert.equal(s.proEntry.route,'overseasDirect');});
test('entire minor season pays minor rate and no major service',()=>{const s=rookie(),roster=simulateDailyRoster(s,0),r=record(s,roster);settleSalary(s,r);settleIncome(s,r);assert.equal(r.paidSalary,450);assert.equal(roster.service,0);assert.equal(s.incomeHistory.at(-1).paidSalary,450);settleSalary(s,r);assert.equal(s.totalSalary,450);});
test('early promotion uses daily pay and connects 40-man/service',()=>{const s=rookie(),roster=simulateDailyRoster(s,1),r=record(s,roster);assert.ok(roster.days.slice(0,14).every(d=>d.status==='minor'));assert.ok(roster.counts.active>0);assert.equal(s.mlbRoster.on40,true);assert.equal(roster.service,172);settleSalary(s,r);assert.ok(r.paidSalary>450&&r.paidSalary<11700);assert.equal(r.overseasPay.majorDays,173);assert.equal(s.salary,11700);});
test('minor service credit never becomes major salary; IL days are paid major',()=>{const s=rookie(),r=record(s,{days:[...Array.from({length:100},()=>({status:'minor',service:true})),...Array.from({length:52},()=>({status:'major',onActive:true})),...Array.from({length:10},()=>({status:'il15'}))],counts:{active:52}});settleSalary(s,r);assert.equal(r.overseasPay.majorDays,62);assert.equal(r.paidSalary,Math.round((450*100+11700*62)/162*10000)/10000);});
test('minor renewal retains split salary; ordinary guaranteed contract exits split pay',()=>{const s=rookie(),r=record(s,simulateDailyRoster(s,0));settleSalary(s,r);s.records.push(r);prepareRenewal(s,r);assert.equal(s.contractOffers[0].annual,450);s.year++;signRenewal(s,'one');assert.equal(s.activeContract.payScale.minorAnnual,450);setContract(s,20000,3,'FA');assert.equal(s.activeContract.payScale,undefined);const paid=record(s,simulateDailyRoster(s,0));settleSalary(s,paid);assert.equal(paid.paidSalary,20000);});
test('legacy overseas saves preserve guaranteed salary and past income, deterministically',()=>{const s=rookie();delete s.overseasContract;setContract(s,18000,3);s.records=[{year:2030,salary:17000}];s.totalSalary=17000;const old=JSON.stringify(s.records);migrateCareer(s);const first=JSON.stringify(s);migrateCareer(s);assert.equal(JSON.stringify(s),first);assert.equal(JSON.stringify(s.records),old);assert.equal(s.salary,18000);assert.equal(s.totalSalary,17000);assert.equal(s.overseasContract.legacy,true);assert.equal(s.activeContract.payScale,undefined);});
test('domestic reemployment retains route and removes overseas pay scale',()=>{const s=rookie();s.stage='pro';setContract(s,3000);assert.equal(s.activeContract.payScale,undefined);assert.equal(s.proEntry.route,'overseasDirect');assert.equal(s.salary,3000);assert.equal(SALARY_MODEL.mlbFloor,11700);});
import {advanceYear} from '../dist/src/engine.js';
test('full engine season saves prorated income and survives JSON resume without salary duplication',()=>{const s=rookie();s.pending=null;for(const key of Object.keys(s.player.abilities))s.player.abilities[key]=40;advanceYear(s);const r=s.records.at(-1);assert.equal(r.stage,'mlb');assert.ok(r.overseasPay);assert.equal(r.paidSalary,r.salary);assert.equal(s.totalSalary,r.paidSalary);const restored=migrateCareer(JSON.parse(JSON.stringify(s)));assert.deepEqual(restored.records,s.records);assert.deepEqual(restored.activeContract,s.activeContract);assert.equal(restored.totalSalary,s.totalSalary);assert.equal(restored.proEntry.route,'overseasDirect');});
