import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createPlayer,retire} from '../dist/src/engine.js';
import {configureStart} from '../dist/src/profile.js';
import {managerEligible,directOverseasProspect} from '../dist/src/career-rules.js';
import {reviewEmployment} from '../dist/src/lifecycle.js';
import {startAfterlife} from '../dist/src/afterlife.js';
import {emptyStats} from '../dist/src/stats.js';
import {TEAMS} from '../dist/src/data.js';
function veteran(seed=111){const s=createPlayer('検証','batter',seed);Object.assign(s,{year:2040,age:37,stage:'pro',team:TEAMS[0],proYears:12});s.teams.push({year:2028,stage:'pro',team:s.team});s.records=Array.from({length:12},(_,i)=>({year:2028+i,stage:'pro',team:s.team,stats:{...emptyStats(),games:130,ab:500,hits:170,hr:25,bb:60}}));s.activeContract=null;return s;}
test('監督は一球団10年以上かつ活躍7年以上のみ。年数だけ・移籍歴だけでは不可',()=>{const a=veteran();assert.equal(managerEligible(a),true);const b=structuredClone(a);b.records=b.records.slice(0,9);assert.equal(managerEligible(b),false);const c=structuredClone(a);c.records.slice(0,6).forEach(r=>r.stats=emptyStats());assert.equal(managerEligible(c),false);const d=structuredClone(a);d.teams.push({stage:'pro',team:TEAMS[1]});assert.equal(managerEligible(d),false);assert.equal(managerEligible(a,TEAMS[1]),false);for(const s of [a,b,c,d]){reviewEmployment(s,{overall:40,stats:{...emptyStats(),games:5}});assert.equal(s.employment.options.some(o=>o.role==='manager'),s===a);}});
test('海外大学直接ルートの自由契約では国内オファーの確率・額・球団数を優遇',()=>{let directCount=0,otherCount=0,compared=0;for(let i=1;i<=300;i++){const a=veteran(i*351);Object.assign(a,{stage:'mlb',age:26,team:'シアトル・マリナーズン',proYears:4});a.teams=[{stage:'overseas',team:'大学'},{stage:'mlb',from:'overseas',team:a.team}];const b=structuredClone(a);b.teams[1].from='pro';const r={overall:50,stats:{...emptyStats(),games:40,ab:100,hits:20,hr:2}};assert.equal(directOverseasProspect(a),true);reviewEmployment(a,r);reviewEmployment(b,r);const offers=s=>s.employment?.options.filter(o=>o.id.startsWith('trial'))||[];const aa=offers(a),bb=offers(b);directCount+=aa.length;otherCount+=bb.length;if(aa.length){assert.ok(aa.every(o=>o.attention&&o.salary>=2000));}if(aa.length&&bb.length){compared++;assert.ok(aa[0].salary>bb[0].salary);}}assert.ok(directCount>otherCount&&compared>10);});
test('100万人達成は一度だけ、YouTuberの文章は連続重複しない',()=>{let reached=0;for(let i=1;i<=250;i++){const s=createPlayer('動画','batter',i*771);s.age=30;s.retired=true;s.postCareer={year:s.year+1,role:'野球YouTuber',team:'',salary:0};const a=startAfterlife(s),hits=a.entries.filter(e=>e.text.includes('登録者100万人'));assert.ok(hits.length<=1);reached+=hits.length;for(let j=1;j<a.entries.length;j++)if(a.entries[j].role==='野球YouTuber')assert.notEqual(a.entries[j].text,a.entries[j-1].text);}assert.ok(reached>40);});
test('選手時代に監督資格がなくてもコーチ3年以上・実績2回以上で昇格する',()=>{let promoted=0,unpromoted=0;for(let i=1;i<300;i++){const s=veteran(i*313);s.teams.push({stage:'pro',team:TEAMS[1]});s.postCareer={role:'コーチ',team:s.team};retire(s);const first=s.afterlife.entries.find(e=>e.role==='監督');if(first){promoted++;assert.ok(first.coachYears>=3&&first.coachAchievements>=2);assert.match(first.text,/指導実績/);}else unpromoted++;}assert.ok(promoted>0&&unpromoted>0);});
test('内野は一二三遊、外野は詳細未選択でも左右中が割り当てられる',()=>{for(const pos of ['first','second','third','shortstop']){const s=createPlayer();configureStart(s,{role:'batter',positionGroup:'infield',position:pos,style:'balanced'});assert.equal(s.player.position,pos);}const positions=new Set(),styles=new Set();for(let i=1;i<100;i++){const s=createPlayer('外野','batter',i*137);configureStart(s,{role:'batter',positionGroup:'outfield',position:'first',style:'random'});assert.ok(['left','center','right'].includes(s.player.position));positions.add(s.player.position);styles.add(s.player.style);}assert.equal(positions.size,3);assert.ok(styles.size>=3);});
test('手動セーブスロット・アーカイブは追加しない',()=>{const ui=fs.readFileSync(new URL('../dist/src/ui.js',import.meta.url),'utf8'),storage=fs.readFileSync(new URL('../dist/src/storage.js',import.meta.url),'utf8');assert.doesNotMatch(ui,/localStorage|archiveCareer|careerArchives|archive-open|slot-save|slot-load/);assert.doesNotMatch(storage,/localStorage|export function (save|load|slots|archiveCareer|careerArchives)/);});
